_target_: REAPS.models.REAPS_model.REAPS_Model

ablation_mode: False        # True for ablation Receptor_Aware Mechanism.
is_fine_tuning: False

backbone_noise_scale: 0.02  # 0.02 /0.10 /0.20 /0.30, this parameter is used for training.
k_neighbors: 32
virtual_frame_num: 3
fourier_dim: 16
positional_buckets: 65
E_idx_embed_dim: 16
hidden_dim: 128
num_heads: 4
encoder_layer: 6
geo_layer: 3
edge_layer: 3

dropout: 0.10
mask_rate: 0.15
lr: 5.0e-5                  # pre-training -> 1.0e-3 / linear_fine-tuning -> 1.0e-5 / cyclic_fine-tuning -> 1.0e-4
weight_decay: 0.1

vocab_size: 21
